/*
 * HTEMP_SENSOR_config.h
 *
 *  Created on: Oct 20, 2021
 *      Author: Omar
 */

#ifndef HAL_HTEMP_SENSOR_HTEMP_SENSOR_CONFIG_H_
#define HAL_HTEMP_SENSOR_HTEMP_SENSOR_CONFIG_H_


 /* Choose ADC Channel:
 MADC_CHANNEL_0
 MADC_CHANNEL_1
 MADC_CHANNEL_2
 MADC_CHANNEL_3
 MADC_CHANNEL_4
 MADC_CHANNEL_5
 MADC_CHANNEL_6
 MADC_CHANNEL_7
*/

#define TEMP_CHANNEL	MADC_CHANNEL_0

#endif /* HAL_HTEMP_SENSOR_HTEMP_SENSOR_CONFIG_H_ */
